### ISSUE TITLE
Güncelleme yapılacak mı?

### ISSUE THREAD

**Issue by ramazansancar** [edevlet/ornek-projeler#2]
Org. ve Repo oluşturulmuş. Ancak son 8 yıldır hiçbir çalışma yok

**Comment by Ahmet-Kaplan** [comment]
Gruptakiler projeden ayrıldığı için herhangi bir çalışma eklenmedi maalesef.

**Comment by ramazansancar** [comment]
Proje ile ilgili kaynak api vs sunulabilirse ben js ile kutuphane veya küçük eklenti tarzı şeyler yapabilirim
